### ISSUE TITLE
快速上手页面中没有说明sbatch提交job是在client还是PI集群中提交

### ISSUE THREAD

**Issue by haibochen** [SJTU-HPC/docs.hpc.sjtu.edu.cn#42]
https://docs.hpc.sjtu.edu.cn/quickstart/index.html  

不确定是在哪儿提交。

提交到 SLURM

$ sbatch hello_world.slurm

**Comment by haibochen** [comment]
实测应该先ssh 到 login.hpc.sjtu.edu.cn上编译和执行。
但是编译过程中报了：

/opt/xalt/xalt/bin/ld: line 334: 17120 Segmentation fault      XALT_EXECUTABLE_TRACKING=no PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin LD_LIBRARY_PATH=$XALT_LD_LIBRARY_PATH $GEN_LINKDATA "$UUID" "`pwd`" "$SYSHOST" "$EXEC" "$SHA1" "$ARGOBJ" "$EPOCH" "$FUNCRAW" "$LINKLINE_OUT" "$COMP_T"

虽然编译后的可执行文件是可以执行的。

**Comment by Winxsss** [comment]
@haibochen 文档中增加了“小技巧”，提示用户登录到π集群。编译问题需要先 `module purge` 后再进行，文档中已更新。
