### ISSUE TITLE
Slurm 作业调度系统 Python文档链接404

### ISSUE THREAD

**Issue by K1nght** [SJTU-HPC/docs.hpc.sjtu.edu.cn#44]
[Slurm 作业调度系统](https://docs.hpc.sjtu.edu.cn/job/slurm.html) 文档的Python文档链接丢失，点击后404，如下图
![image](https://user-images.githubusercontent.com/41949112/148497772-cea33ae7-62d4-43f7-a661-882c74b2083c.png)

**Comment by Jack-Hu-2001** [comment]
同这个问题，好多人都在反映但是没人理

**Comment by Winxsss** [comment]
@K1nght 已更新Python文档链接

**Comment by K1nght** [comment]
> @K1nght 已更新Python文档链接

感谢！
