### ISSUE TITLE
英文版本

### ISSUE THREAD

**Issue by Jack-Hu-2001** [SJTU-HPC/docs.hpc.sjtu.edu.cn#45]
实验室来了国际留学生，想看英文版的

**Comment by zhoujing2021** [comment]
你好，英文版文档正在准备中。请先用浏览器提供的“翻译”功能浏览文档。
<img width="961" alt="1" src="https://user-images.githubusercontent.com/93113340/203484067-353c50df-6f33-4808-879b-a57b306a4a4c.png">

**Comment by wangyichao** [comment]
> 实验室来了国际留学生，想看英文版的

英文版Getting Started已经上线：https://docs.hpc.sjtu.edu.cn/en

**Comment by Jack-Hu-2001** [comment]
不错！做的非常好！感谢学校的超算团队，辛苦了呀！
