### ISSUE TITLE
Is HPC Studio open-source

### ISSUE THREAD

**Issue by ChufanSuki** [SJTU-HPC/docs.hpc.sjtu.edu.cn#46]
I'm planning to set up a slurm cluster for my lab. HPC Studio can greatly help students who are not comfortable with Linux terminals to use the cluster. Is ai studio open-source?

**Comment by weijianwen** [comment]
studio.hpc.sjtu.edu.cn is based on an open source HPC portal OpenOndemand https://openondemand.org . An alternative portal developed by Peking University named SCOW can be found at https://github.com/PKUHPC/SCOW .
